apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapiiiuk
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simpleapiiiuk
    spec:
      containers:
        - image: myapi:1.0
          imagePullPolicy: Never
          name: myapi
          ports:
            - containerPort: 8080