dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker

before_install:
  - chmod +x mvnw

env:
  global:
    - secure: "FD7g6vPtiDEejrlAGuShYjNrmNx4RUxlFh8FMY/GJfEc8eQLKZtP4B76ahw2TzzsSEVrvQhjgyPdFMfB7x8xxQYS1huORNGxathqNVykX4EXKp2UofCulHvcEm6IOjjLAQYQ+U/mPY0nWGpZWO3jjwdGIQck2SGk9cWjnCQ18cBesKfbkXTQIzlFRvns1stMMJQmQJgcAh8CezkEzVRP50IH/prVVZ9ypLcioy5mpde3Tuj2sDNUJcP1sE2J+vuebsfGr7tzDVByDeN9Pz3VpvQNYKU4gMkkWHVebrgIanRYhpSzjuf4fD9mCFZkIfoeBaucf0qWVvtAcDrpVftHTewAJXDEhu8MUkpHel19LCnlXxSFxWDduwrgmOOZFNU9P9WDeaVkkO4W/Kdln0W2YtS4eFLf6PssKl+QGM4dgs/u5Ft1yfuIcJ/Rs91CpPMzsW/wBFFd1UCTlLsQOAe77gwAeQsBrR0ns5nk1qI8C+pqUl/yH9LWB8CY8RllbdrLU/6HnonchZrUq/s0tK2SyDcCw9sdu0Ftr8bWpaivhWFzKY4telnUwkrzDGZ2s94PzP+LLu1p5Yy3YANhDME8p03StFxUSWobNjm8kwQUlQHRGvYdHReXtiT0OzxDqgGf+CifUI4n1Ae4Gd5vBARUpjq7BNAY6kH0k9ObydJeeGY="
    - secure: "TSkHJbN8vYPPuZ8Gyn1VXnKcBkbhPohZ7MLpmpm0oY5fzhHX16u/zxyZ6MnSwyzOXg245Ija8zIjAuuHqbDDBzXj3PATWAizOBGK1Q41qHRaQB0izz+mX8yWN9yhs33DFSjZ/mmb/qfBD6NkvreC6wB1AsxK/NlB3VT4ccudwuBbDvwhPa1dhT8hvL/kAuG/54QVmAlQ2+pzAIMOFo/jFmm9Iqp17aUUAvOhutyPWtB8Kdb8Hv0r5BpcUKZms4+SpMBx1j+I59jqKi13ZrKZ7omB0TnrVchskCU6PrraRedIzjkmsjetRDkmy+SPkrBVQyCXc27/yYRHk7gncwj7a5tMdb+7uBE9XF34MwiRAZXv8FARYqKKLf/Fg1Oh3mWI6OE4//CYvTlBU7gwqO5gShW2fWIcnf0iYhT8J4ITBzBf9c0+uDnyjhuq271nx37p0F9IxIlm7y/bx06UDpAoxCaEdSzJrtL1VEPPgkioQ/V7TwtwQRtHhTNRbjGAOLZNDfxvCWlPshNzRG/xPPDLu+f5QsqGqT4vgWqnbqwMeHLB5qdLMIvXZKzYqu0De/004R7QfMCYSlU3YcM7WRCgQZ8Xx3xADvaciEDEBuzbmBxSu/XzQimWqSI7oN8a+CVO1l4uAZLG1AucTtYfH++5ag1Rh6o+n5ZfF1jdTl8tL74="
    - secure: "W7vprQAnyjFGVN9h+CpqVStjYGI+Vsq6p5V33LC+LPP91t3w9cx9KtAqUPL+DHJGtO9GL7IWJM1ellkwXphw4XqxeF8OBCmjEI+sULGJzhNqfOzH/On+PG8nFBPe6rz39rdaiXmNGI3eXqOXuaadgAGTc87/0xVBnwrCkU01MfZ52WWJw5N+0xSZ3ftD2Ih2BebRupLWvNy1S8hqnoV/g8NWdM9eKXQUZEd8aDX3YxGHFyI7x112K/h9tQ3uz7WSykllWmfJ2H/VeOWYPbpGF1QFy3X/enBEuZF31Zfwwib0DzQq1hWFcY6ihmovm5W35Ko3049feTZXCqGm6WhXN06V0VY2JpM9crf3UzWhpErEnNaSct6ZZEW5AlUJVRzRFR7dbtjyR13tccTDKct5UJF/AHKN/HXOyw/cfNYRoJwLIlZm9kfxTDoMHCHT/Jkd2e1cWWDirKrGTrxzlzsh+YnJjdJ02lVOVZq8Wq+lipnHSiop7Jqkhpbb1/+g0QNGJYSuT2wpfrwFpONYKHF4NzRp3+S5X4fKK3MA8uv8p2mCSUe+NIQyh9aAumzrOUyvSqGs//sSQWbyiHY4AWbG9QMt/l3TyEsMBjAVZVWGx+tewKmUOaoeoXoV9lmTWK9jha1Ni0/5uy3G/BOLY36PwWYACasuJfxJ5sKmD2krXCo="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=simpleapiiuk/repository-iuliia
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: simpleapiiuk

