dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker

before_install:
  - chmod +x mvnw

env:
  global:
    - secure: "GAmcahhQvJBRMjDuF47O1c8rALQmBEHRwlMD4tsl7eLs6LthOTpv5kMUs/PlcFpaZnjDMRfEgVwKaEnkyngItbHiZgvI7q11LO1B1PrzrYMI9g7Gu/cwznVbsSnqRE0L0iw1XpQDk0Oyf3C7cz/HnPXQqTR1/b0vAPeKGtaFVUywSYgVxDST+NBGMfdgrcgOnZAvrrNwp8SJG2DCKrfismKKReTtSRX8WT+8Jkt0TkmA0okj9TOg6r2WZio02ytzn6vRCXKrlFdVJ17g05ZTZfaiGlT+BvCBoYGOWoZu6FfeydRxeK6odmTRtkBBvvc3GwA54DJBuh4nRcheuBhOV3qut3PGpNvQeAaqeekDCGty6hWBtyfyGGUY8AsUOvThMrLqqaZcMRPFKGIjZXjd91piFXffEBUU+P5wn/sQiH681fokRRPe+6iWc5ma7P3VMozAdLO4hgdm8PkOqFluOvg+msLl77g1qTRKNh82IdWEnT5Lovu2AgJh8wUUuc6pfO3gT55QVg0FQr1ICJJroor8bQTZgsB3n0aXeX1NPA+/DbpadRFkvETpFP5fAEoIG/mEbaKhZgqzsgIu39EqbSTITpO4n4THZL39Zb81iRJknrf7PjnJd7ULl8jHioLEI/ox1PgxJVpY+oonATzuvUTVgOg1NFzC/jgIaYb3Fzc="
    - secure: "HCIibN/xrx/1ctAtkZLhd0G+nN0cC51yprb26Kd0mPQYlqKyruxBJ//JDcnIIKUItq8EQ2ayF8p1rXo4y9E4/5hwOGiPONU4HYoPdy/J/lrZiAq7chjAxgmWfie2+pUCHoXDFswncxpWvonf0Q144qRgehUHMR7Zsb1+h85Pf4AaZqoDd1YgqcCwcvfOQr5sOzI9du13U+OYVq1+0QVJ9JvL1J+MerFiovNBtfCNtCXYOVOXjLOEPXel095xaSwDDG5MHepZX5HVCvpKSp3MqvHNhn0kKbtfsh5emYhLiWmczUDD+CuxK/JFjFIsjlV1fXXIFIfH7l1N08UC5wg/Lr+v1qo8Kgzlj8H2u6C6bmLTpkED5GoQCZj85gT0jdFXQMxlAGzAngDGft0HOfQlLqQsd0xpN1TTDz29ogbkGNePbsxcY3y6GO57KzpYd6kUOXZYaMy9rnv/EV3UZ8EQ4LjdfjyqWGgPh7gq9BJIvPq8h6Dypp0bUieejxrOBtvF67u3zuw1kI/q9+miKz7/PBIl0FFH5LFcSxitXQfCNf6SIhPtmF4dUURO0TX75VC+2c9AUeFzolQulF7TsH2fKn52zG693qktIWETE8EqOyeNhDpIwmU/5QLZem5ePpduumN+ekZNkADA3mlAz7t10lTdsdtcwABsyTDrnm8JU/4="
    - secure: "pXsUoZa5X75ZdSGc1eIu+yaoZWG9y3lEFFy5UYYUuvxHtlZ62BRQ1ZiR72/11lfFGZvx2T6WgD7n9jCI0aj0vwMH/endecypRWcbEA3kldDhz0Nw+TpKlJqWUFvi+ZdbYMzKvMu/WqN9zs/34FUMXsiYJ7vKebnvatKaKYNQH/ZoXjEAoslZAwjb171uLIjCCcZhMe+0lyD++yRXZo5nE+vMVUNu2EhngKGsKgdwDR0JWXXQ7IV/uKBW889lN3iSyYltwY9kwcc9O1SPJEsuYWtxLSdhyCSEa68l2QdEYxKWs05PrAXhIIpq+1VodFur+UzHhMNkas1LI3pLLYEx04oexvQyQ94AbeFJKQF7/4aCwU0qmTLAq+M5m7JcHkWqHd4CPExtdOgD8t150ukJuCkFlPQCMPLOPToYjXAQs/HwNffrXm9k9UGeQyi1nGQyx7tLMwXdUgfcrFBw1ywL6H+OR3ZztTaPryqcSZgxMDWPUUlk+1FOD0KH/7vmxFu5eJWk7o2NpQo5oAzWW1mnan2E5Do6z90Z6KGu/OvS7ErcJxs5+sG1RZC6zWXzPKjTA+xTORppUTnEtrLVp9oKJQrtu7TKEVNQHowxokKGoDdYxJbgBzbT+/28x3SDn6SsrjxPtk8GJBDahT+6/yJJQ7L92Cl5PJy0Nu/BHkoiXzk="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=35874569/my-docker-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: simpleapiiuk

