dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker

before_install:
  - chmod +x mvnw

env:
  global:
    - secure: "pXxSuvcL1vfp3doAtnCa7Zzq+JzH1ZSxp/LtsE0j/sDY4G37jMwiqzMR5PBKKCXZGd35odxtXi50XI0RMIvk1jwt6KquDYtxfxkPF3hq33YHV/spCCjMYIH5zJIABBJsDlIzmfhfEM0LD6jjdbgVj/x1irEaQadhRnAqYExVKZftmmdQr91QWlbl5mrcYvxefBpz0Cx8zheQ0G/OsMBq5SPggl5IhLV0Yt6PkwSISLqLrsbA0XGo3eSaY+BqmWFFeLVfZ6GZFRs7QDm02PSdt7HJWa7HvpqM5vuIvgQaiINgq/QcnkqcrN4BJQUqenomRoRlxzfd4at/lgtd4dT5WMtOao5tHNwacn5faSmKxjL93XfJzT2CsFcD7pKWbymOXqKdGLEZsuusXlPI8SHYTU6UT8KqucDyGPHNawoutPPN+toCjrs9TThTopRhCxnRfGcRGE1Be7SLJSK+Dn7nBNhuZSI1mPoTG0PJu8/2HbwlKRbB858hyRGZQU0yjc6kYjgBjUnmeykWEF1EHQeoF84NjOxICiy9nT08VJSgvb4Kqe9SG23fLeLp2XkVSKrhHPwoJ8jrMpv1pk1G2L1PDTrkyDRUCL5N59EpYexifpx4IUTTaFKE6xtgnQfwJ8WRA/qYZu3NOe+4nrg1mITL5g7dEjXANytl/oLN9ISytb0="
    - secure: "RTXCmK4DTMJaISLtd+K8iWiGppjAGWeEAEmuqJwYdt/OQEK6e+cXULhBkcEZ8qPS8FQUeeYl23eIYKKXhI7tjPcrN9DHdVu8Ono0yX6wBd+Fl6yIwg36Bqaq0olvcOYNQwe300LEocYWHNzUcjzoHlCVCmUx4QrVfqBhkB63xnUNtBe6Xdl3vit91w7BkilyTQaRMsme94A0wkuxzDO5G5NOe4sk33iBuzXD1f9py2iv8lCEQ3RX7ModTp/PUD7VYQBdpW/kePXEOFfR/qVTpCuCF+KTiOsdFZdt7YpC08ysDsIAL/Sv0Fohvy/YKvpiq0pj1PlHvIpqsRR9yY6qpOTbPJTg+Uo0tVJFXdunVas1qnb776lrQx1e1ZQ+9dv9+BqGJ6bfv8S7y50ro6x7QavU213ohH9o9qu3OnbxybDiJUSx2o9Q4+4B0LwmSXFgjNxJVmkvcaj0mHPBtj8O4NWV/Ai8yx2dIZWh50EJD2p+UM6h36zx/UNUsA+MIgAzL5uwqi/crp32Nl+Sz90WV+zTBjuRAH2ceOqtsPbTjCNBqDr6qsZmzpsmE3cUgxNYI86VORm/73/CB3XIzq0hGAM7EBVbqgaPEEZo5Y8h7fo1S30Iy86vJ2Rz7ZkJ1oZT4NOw9ysnziXqpvVyOwv7SE0akFzTHkhJ+vDrfUdvUPA="
    - secure: "DAiNlgp1MrMkV6Lklo+bQTjGMC2H8of3RHkjU/7mtGOroDtumPc2KXY5OuH7TzD+yeN06kh02o3R1XNBXylO6azzwTBXpHOR22nw2S8regaMNyJHGrEYHFAKsVyuIWnAzEtKsiGaVvyDBNwQnYBdgvHCbMJ0bGC19+tijkgVEny7rWTClcRH1nNBS2A5l8tG7bfYkbvoTIDbT9J7h7f1+buPf54og63Kpw1Yl/REmyfz0ZLTn0tskWveNEm4rc6DTqaRU+V6t4YVwQjJBK3Fum+T9+oE9HJtPLb0Ho3H5u6e3hhU4lsbUzhCLCZJPyf93/aMsSC8jFzlj7hA3LZSTar5Ejz07xrQP3/SZFAeyEopW573laI0qocuX5N0dQu8vaSn208CH93TVxeORKDSqRxtj0JMQGTbDQH6N+EDPKvo0/7i+DbR6TNAZN89quIKTDhujmfryB8uv+vlDIayaOFN3776bdxLJJqqwlk9G+7jK0dnnq7Pf8hXbA0HoIVpRt9LNVniBCI78/RJOOcbADSbMsFK77X6yKCT/XR9R1JdjHWQL5pz7QQWrnLuZrPJgktlSGMaCsgdGWQT0QO090u3xiPpsogyOSY5S1mPvrJb3bhFDL4bJFZeX7Yc+iiJvOgyjWOsus43/bAY+7kFTVi7lifPLoG0iTwZ+tPD3ck="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=simpleapiiuk/repo_iuliia
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: simpleapiiuk

